FROM searxng/searxng:2025.3.25-2ad987c71

# Copy in searxng settings file
COPY searxng-settings.yml /etc/searxng/settings.yml

# Copy in searxng limiter file
COPY searxng-limiter.toml /etc/searxng/limiter.toml
