FROM searxng/searxng:2025.3.11-3fe602a46

# Copy in searxng settings file
COPY searxng-settings.yml /etc/searxng/settings.yml

# Copy in searxng limiter file
COPY searxng-limiter.toml /etc/searxng/limiter.toml
