name: Docker Build and Push Client Container Image

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit hash
        uses: prompt/actions-commit-hash@v3
        id: commit

      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Convert repository name to lowercase
        id: lowercase
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.lowercase }}:${{ steps.commit.outputs.short }}-${{ env.DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
